
println("Profile Collective Assembly Performance")
print(" E 3-body old:" ); @btime ([energy(b, at) for b in B3])
print(" E 3-body new:" ); @btime energy( B3, at )
print(" F 3-body old:" ); @btime ([forces(b, at) for b in B3])
print(" F 3-body new:" ); @btime forces( B3, at )
print(" E 4-body old:" ); @btime ([energy(b, at) for b in B4])
print(" E 4-body new:" ); @btime energy( $B4, $at )
print(" F 4-body old:" ); @btime ([forces(b, at) for b in B4])
print(" F 4-body new:" ); @btime forces( $B4, $at )
print(" E 5-body old:" ); @btime ([energy(b, at) for b in B5])
print(" E 5-body new:" ); @btime energy( $B5, $at )
print(" F 5-body old:" ); @btime ([forces(b, at) for b in B5])
print(" F 5-body new:" ); @btime forces( $B5, $at )
